name: test actions
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test
      - name: print the result
        run: echo "The result is ${{ steps.test.outputs.result }}"
